### ISSUE TITLE
IE on Windows XP no longer supported

### ISSUE THREAD

**Issue by philklc** [etianen/html5media#63]
The server where html5media.min.js is hosted is HTTPS only, going to the URL by HTTP redirects the user to the HTTPS domain.

I remember using html5media two years ago which it seems to still work fine, but now the SSL certificate used on the server only works in browsers with SNI support, which is not supported by IE on Windows XP.

**Comment by etianen** [comment]
Ah, yes, that would seem to be the case.

I'd suggest hosting your own html5media.min.js if you need to support IE on XP.
