### ISSUE TITLE
mobile video cant played (os ios)

### ISSUE THREAD

**Issue by panlita** [etianen/html5media#66]
video src like this  www.xxx.com/video/video123456;
(some thing strange is that video file **with no suffix**).
window chrome /fire fox/IE & android chrome could worked fine.

but on ios phone/ipad video cant played. help maybe.

thanks.

**Comment by etianen** [comment]
Have you worked through this: https://github.com/etianen/html5media/wiki/Embedding-video#providing-a-version-for-mobile-phones

**Comment by fanfavorite** [comment]
This is an iOS issue and not script related. iOS is weird when it comes to video URL's without the extension. If you can include the extension, do so, otherwise try to search for iOS bugs related to this on the web. There are workarounds that might work for you.

**Comment by etianen** [comment]
Closed, after @fanfavorite explains things!
