### ISSUE TITLE
html5media.js:409 Uncaught ReferenceError: DomReady is not defined

### ISSUE THREAD

**Issue by coubmd** [etianen/html5media#69]
html5media.js:409 Uncaught ReferenceError: DomReady is not defined

**Comment by etianen** [comment]
You're using the uncompiled source. Either hotlink to //
api.html5media.info/1.2.2/html5media.min.js, or use the scripts found in
the dist/ folder of the respository.

**Comment by JayenLee** [comment]
Video can not be downloaded while playing, how to do?
