### ISSUE TITLE
there is a bug, if set video label's width "xx%" or height "xx%".it not work in IE8

### ISSUE THREAD

**Issue by w8w8w8** [etianen/html5media#71]
I  fix it like this:
` function getDimension(element, dimension, fallback) {
        var result = element.getAttribute(dimension);
		if(result.indexOf("%")){
			return result;
		}
		if(result.indexOf("px") || result.indexOf("PX")){
			return result;
		}
        if (result) {
            return result + "px";
        }
}`

**Comment by etianen** [comment]
The `width` and `height` attributes on a `<video>` tag don't take units. They are specified in pixels.
