### ISSUE TITLE
How to get the current playback duration and set the playback progress？

### ISSUE THREAD

**Issue by Zegapaiz** [etianen/html5media#76]
I want to create a music player based on this library, including style customization, previous and next song switching, custom progress bar and other functions.

 Does this library provide an interface to operate the player? If not, can you give me some relevant suggestions? (Requires support for IE8)

ps： Only found play and pause functions
```
         <audio id="myAudio" onplay='startPlay' src="http://zhangmenshiting.qianqian.com/data2/music/4a53fed748a2ac2968d0eb090e692f6b/579625605/579625605.m4a?xcode=5386bd6a814b8e6ed1fcd5f6c50b1ab0" controls autoplay></audio>
        <button onclick="startPlay()">播放</button>
        <button onclick="stopPlay()">暂停</button>
        <script>
            var x = document.getElementById("myAudio");
            console.log(x)
            function startPlay () {
                console.log('播放')
                x.play()
                
            }
            function stopPlay() {
                console.log('暂停')
                x.pause()
            }
        </script>
```
![image](https://user-images.githubusercontent.com/12904995/37384724-5ee8178c-278b-11e8-85bd-bf79df1e7042.png)

**Comment by etianen** [comment]
No, this library is a very simple shim, and is optimized for fast loading
and ease of use.

If you want a more comprehensive player with a programmatic API that works
in IE8, you'll have to do some googling. :)

**Comment by Zegapaiz** [comment]
@etianen Thanks
