### ISSUE TITLE
.amr and .flv can we play with html5media

### ISSUE THREAD

**Issue by HippolyteSagittaHU** [etianen/html5media#77]
I try with .amr and .flv file by our function, bad luck, can not play. and .m4a is ok.

Could u help me for these two type audio file to play.

Thanks.

**Comment by etianen** [comment]
I'm afraid that html5media does not support those video types.

**Comment by HippolyteSagittaHU** [comment]
.flv is a video type, i got it, bak luck for not support. .amr is an audio type, it can be use as a voice message on the mobile app, so about this audio file, thanks.

**Comment by HippolyteSagittaHU** [comment]
and a read one closed issue, u said "html5media will only work with video types that are based around the MP4, OGG and WEBM standards.", could u help me to show all support extension name list. thanks.

**Comment by etianen** [comment]
mp3 ogg oggv mp4 m4v

Maybe a few others.

**Comment by HippolyteSagittaHU** [comment]
got it, thanks
